name: CI

on:
  push:
    branches:
      - feature/ci # only for testing
  pull_request:
    branches:
      - feature/ci # only for testing

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup environment
        run: |
          cd chromium-library
          curl https://github.com/google/google-java-format/releases/download/v1.13.0/google-java-format-1.13.0-all-deps.jar -o google-java-format-all-deps.jar
          cd chromium_subp
          curl https://cef-builds.spotifycdn.com/cef_binary_3.3497.1841.g7f37a0a_windows64_minimal.tar.bz2 -o cef_win32.tar.bz2
          7z x cef_win32.tar.bz2 -o"cef_win32.tar"
          7z x cef_win32.tar/cef_win32.tar -o"cef_win32"
          mv cef_win32/cef_*/* cef_win32

      - name: Build subprocess helper executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path ./chromium-library/chromium_subp/Cargo.toml

      - name: Build native library
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path ./chromium-library/chromium_swt/Cargo.toml

      - name: Copy libraries
        run: |
          cp ./chromium-library/chromium_swt/target/release/chromium_swt_6900.dll ./com.equo.swt.chromium.win32.win32.x86_64/chromium-3497
          cp ./chromium-library/chromium_subp/target/release/chromium_subp.exe ./com.equo.swt.chromium.win32.win32.x86_64/chromium-3497

      - name: Generate Rust CEF Bindings
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features gen --release --manifest-path ./chromium-library/chromium_subp/Cargo.toml

      - name: Generate Java CEF Bindings (Cargo)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features genJava --release --manifest-path ./chromium-library/chromium_subp/Cargo.toml

      - name: Generate Java CEF Bindings (Java format)
        run: |
          cd chromium-library
          ls
          ls chromium_subp/target
          java -jar ./google-java-format-all-deps.jar --replace ./chromium_subp/target/CEF.java
          mkdir ../com.equo.swt.chromium/bin/org/eclipse/swt/internal/chromium
          cp ./chromium_subp/target/CEF.java ../com.equo.swt.chromium/bin/org/eclipse/swt/internal/chromium

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chromium-swt-target
          path: chromium-library/chromium_swt/target

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chromium-subp-target
          path: chromium-library/chromium_subp/target
