name: CI

on:
  push:
    branches:
      - feature/ci # only for testing
  pull_request:
    branches:
      - feature/ci # only for testing

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup environment
        run: |
          cd chromium-library/chromium_subp
          curl https://cef-builds.spotifycdn.com/cef_binary_96.0.18%2Bgfe551e4%2Bchromium-96.0.4664.110_windows64_minimal.tar.bz2 -o cef_win32.tar.bz2
          curl https://cef-builds.spotifycdn.com/cef_binary_96.0.18%2Bgfe551e4%2Bchromium-96.0.4664.110_windows32_minimal.tar.bz2 -o cef_win32_x86.tar.bz2
          7z x cef_win32.tar.bz2 -o"cef_win32.tar"
          7z x cef_win32.tar/cef_win32.tar -o"cef_win32"
          7z x cef_win32_x86.tar.bz2 -o"cef_win32_x86.tar"
          7z x cef_win32_x86.tar/cef_win32_x86.tar -o"cef_win32_x86"
          mv cef_win32/cef_*/* cef_win32
          mv cef_win32_x86/cef_*/* cef_win32_x86
          del cef_win32.*
          del cef_win32/cef_*
          del cef_win32_x86.*
          del cef_win32_x86/cef_*
          ls
          ls cef_win32
          ls cef_win32_x86
          

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path ./chromium-library/chromium_subp/Cargo.toml

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chromium_subp-target
          path: chromium-library/chromium_subp/target
