name: CI

on: [push, pull_request]

jobs:
  windows-32:
    name: Windows 32_x86
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup environment
        run: |
          cd chromium-library/chromium_subp
          curl https://cef-builds.spotifycdn.com/cef_binary_100.0.19%2Bgcd1e788%2Bchromium-100.0.4896.88_windows32_minimal.tar.bz2 -o cef_win32_x86.tar.bz2
          curl https://repo.maven.apache.org/maven2/com/google/googlejavaformat/google-java-format/1.6/google-java-format-1.6-all-deps.jar -o ../google-java-format-all-deps.jar
          7z x cef_win32_x86.tar.bz2 -o"cef_win32_x86.tar"
          7z x cef_win32_x86.tar/cef_win32_x86.tar -o"cef_win32_x86"
          mv cef_win32_x86/cef_*/* cef_win32_x86
          rustup target add i686-pc-windows-msvc

      - name: Build subprocess helper executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=i686-pc-windows-msvc --manifest-path ./chromium-library/chromium_subp/Cargo.toml

      - name: Build native library
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=i686-pc-windows-msvc --manifest-path ./chromium-library/chromium_swt/Cargo.toml

      - name: Copy libraries
        run: |
          cp ./chromium-library/chromium_swt/target/i686-pc-windows-msvc/release/chromium_swt_10000.dll ./com.equo.swt.chromium.win32.win32.x86_64/chromium-3497
          cp ./chromium-library/chromium_subp/target/i686-pc-windows-msvc/release/chromium_subp.exe ./com.equo.swt.chromium.win32.win32.x86_64/chromium-3497

      - name: Generate Rust CEF Bindings
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features gen --target=i686-pc-windows-msvc --release --manifest-path ./chromium-library/chromium_subp/Cargo.toml

      - name: Generate Java CEF Bindings (Cargo)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features genJava --target=i686-pc-windows-msvc --release --manifest-path ./chromium-library/chromium_subp/Cargo.toml

      - name: Generate Java CEF Bindings (Java format)
        run: |
          cd chromium-library
          java -jar ./google-java-format-all-deps.jar --replace ./chromium_subp/target/CEF.java
          mkdir ../com.equo.swt.chromium/bin/org/eclipse/swt/internal/chromium
          cp ./chromium_subp/target/CEF.java ../com.equo.swt.chromium/bin/org/eclipse/swt/internal/chromium

      - name: Build jars
        run: |
          mvn clean package
          mkdir target-jars
          cp ./com.equo.swt.chromium/target/*.jar ./target-jars
          cp ./com.equo.swt.chromium.win32.win32.x86_64/target/*.jar ./target-jars

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chromium-swt-target
          path: chromium-library/chromium_swt/target

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chromium-subp-target
          path: chromium-library/chromium_subp/target

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target-jars
          path: target-jars
